sudo: required

services:
  - docker
  
install:
  - travis_wait 80 docker build -t fluxcapacitor/pipeline .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - travis_wait 30 docker push fluxcapacitor/pipeline
